// @ts-ignore — virtual module generated by Vite plugin at build time
import allTypes from 'virtual:type-strings';
import { Highlight, themes, type Language } from 'prism-react-renderer';

interface TypeSourceViewerProps {
  /**
   * Path to the source .ts file
   * @example "./packages/ui-kit/src/components/Table/types.ts"
   */
  filePath: string;
  /**
   * Type name to display
   * @example "TableConfig"
   */
  typeName: string;
  /**
   * Return value as string instead of rendering
   */
  asString?: boolean;
  /**
   * Code to prepend before the type definition
   */
  preSource?: string;
  /**
   * Code to append after the type definition
   */
  postSource?: string;
  /**
   * Language for syntax highlighting
   * @default "tsx"
   */
  language?: Language;
}

/**
 * Renders a TypeScript type definition from a source file.
 * Data is loaded from the virtual module generated at build time.
 */
export const TypeSourceViewer = ({
  filePath,
  typeName,
  asString,
  preSource,
  postSource,
  language = 'tsx',
}: TypeSourceViewerProps) => {
  if (!filePath || !typeName) {
    return null;
  }

  const key = `${filePath}$$$${typeName}`;
  const type = allTypes[key] ?? '';
  const finalTypeSource = `${preSource ?? ''}${type}${postSource ?? ''}`;

  if (asString) {
    return <>{finalTypeSource}</>;
  }

  if (!type) {
    return (
      <pre style={{ color: '#c44', padding: '1em', background: '#fff0f0' }}>
        Type not found: {typeName} in {filePath}
      </pre>
    );
  }

  return (
    <Highlight theme={themes.vsLight} code={finalTypeSource} language={language}>
      {({ style, tokens, getLineProps, getTokenProps }) => (
        <pre
          style={{
            ...style,
            padding: '16px',
            borderRadius: '6px',
            overflow: 'auto',
            fontSize: '13px',
            lineHeight: '1.45',
            fontFamily:
              'ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, monospace',
          }}
        >
          {tokens.map((line, i) => (
            <div key={i} {...getLineProps({ line })}>
              {line.map((token, key) => (
                <span key={key} {...getTokenProps({ token })} />
              ))}
            </div>
          ))}
        </pre>
      )}
    </Highlight>
  );
};
